# Generated by Django 5.2.15 on 2026-06-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paper",
            name="page_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="pdf_size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="paper",
            name="processing_percentage",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="paper",
            name="processing_time",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
