# Generated by Django 6.0.4 on 2026-06-13 06:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteratureReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('introduction', models.TextField()),
                ('existing_approaches', models.TextField()),
                ('comparison_of_methods', models.TextField()),
                ('limitations', models.TextField()),
                ('research_opportunities', models.TextField()),
                ('references', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('papers', models.ManyToManyField(related_name='literature_reviews', to='papers.paper')),
            ],
        ),
    ]
