# Generated by Django 5.2.15 on 2026-06-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchgap",
            name="difficulty_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="researchgap",
            name="impact_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="researchgap",
            name="novelty_score",
            field=models.IntegerField(default=0),
        ),
    ]
