# Generated by Django 6.0.4 on 2026-06-13 06:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gaps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIdea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('problem_statement', models.TextField()),
                ('proposed_methodology', models.TextField()),
                ('expected_outcome', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('ADVANCED', 'Advanced')], default='MEDIUM', max_length=20)),
                ('innovation_score', models.FloatField(default=5.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_gap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_ideas', to='gaps.researchgap')),
            ],
        ),
    ]
