# Generated by Django 5.2.15 on 2026-06-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectidea",
            name="difficulty_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectidea",
            name="estimated_timeline",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="projectidea",
            name="impact_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projectidea",
            name="novelty_score",
            field=models.IntegerField(default=0),
        ),
    ]
